"""Relasi Product Tabel

Revision ID: 26712b2b9a29
Revises: e10274a45c7e
Create Date: 2025-08-13 08:08:13.428950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26712b2b9a29'
down_revision: Union[str, Sequence[str], None] = 'e10274a45c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###

    op.create_table('products',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nama', sa.String(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.Column('deskripsi', sa.String(), nullable=False),
            sa.Column('kategori', sa.String(), nullable=False),
            sa.Column('stok', sa.Integer(), nullable=False),
            sa.Column('rating', sa.Float(), nullable=False),
            sa.Column('image', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_table('orders',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('customer_name', sa.String(), nullable=True),
            sa.Column('customer_email', sa.String(), nullable=True),
            sa.Column('total_price', sa.Float(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_table('order_items',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('order_id', sa.Integer(), nullable=True),
            sa.Column('product_id', sa.Integer(), nullable=True),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
